# Generated by Django 2.1 on 2018-08-25 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VESSEL',
            fields=[
                ('project_number', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='ASV Project Number')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('slug', models.SlugField()),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/vessel/cover', verbose_name='Vessel Image')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Modified at')),
            ],
            options={
                'verbose_name': 'Vessel',
                'verbose_name_plural': 'Vessel',
                'ordering': ['-created_at'],
            },
        ),
    ]
