# Generated by Django 2.1 on 2018-08-25 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_object', '0002_auto_20180825_0132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vessel',
            name='id',
        ),
        migrations.AlterField(
            model_name='vessel',
            name='project_number',
            field=models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='ASV Project Number'),
        ),
    ]
