# Generated by Django 2.1 on 2018-08-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physical_object', '0004_auto_20180825_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vessel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
